/**********************************************************************************************************************
 * FILE: Flash_IP_Cfg.h
 * Generated by AUTOSAR Mem Configurator 2.0.0. Do not edit manually.
 * Project AUTOSAR release: R25-11
 *********************************************************************************************************************/

#ifndef FLASH_IP_CFG_H
#define FLASH_IP_CFG_H

#include "Std_Types.h"

#define FLASH_IP_BASE_ADDRESS       0x08000000UL
#define FLASH_IP_TOTAL_SIZE         0x00080000UL
#define FLASH_IP_SECTOR_COUNT       8u
#define FLASH_IP_ERASED_VALUE       0xFFu

typedef struct
{
    uint32 StartAddress;
    uint32 Size;
} Flash_IP_SectorType;

extern const Flash_IP_SectorType Flash_IP_SectorTable[];

#endif /* FLASH_IP_CFG_H */
