/**********************************************************************************************************************
 * FILE: Mem_Cfg.h
 * Generated by AUTOSAR Mem Configurator 2.0.0. Do not edit manually.
 * Project AUTOSAR release: R25-11
 *********************************************************************************************************************/

#ifndef MEM_CFG_H
#define MEM_CFG_H

#include "Std_Types.h"

/* MemGeneral */
#define MEM_DEV_ERROR_DETECT            STD_ON
#define MEM_VERSION_INFO_API            STD_ON
#define MEM_INDEX                       0u

#define MEM_INVOCATION_DIRECT_STATIC    0u
#define MEM_INVOCATION_INDIRECT_STATIC  1u
#define MEM_INVOCATION_INDIRECT_DYNAMIC 2u
#define MEM_INVOCATION                  MEM_INVOCATION_DIRECT_STATIC

#if (MEM_INVOCATION != MEM_INVOCATION_DIRECT_STATIC)
#error "Only MEM_INVOCATION_DIRECT_STATIC is implemented by this reference Mem driver."
#endif

#define MEM_MAIN_FUNCTION_PERIOD        0.005f

/* MemInstance */
#define MEM_INSTANCE_COUNT              1u
#define MemConf_MemInstance_MemInstance_0   0u
#define MEM_INSTANCE_0_START_ADDRESS    0x08000000UL
#define MEM_INSTANCE_0_SIZE             0x00080000UL

/* MemPublishedInformation */
#define MEM_ERASED_VALUE                0xFFu

extern const uint32 Mem_ErasedValue;

#endif /* MEM_CFG_H */
