/* ========================================================================== */
/* FLASH IP HARDWARE CONFIGURATION (STM32F401RE)                              */
/* Generated by MCAL Configurator Tool - DO NOT EDIT MANUALLY                 */
/* ========================================================================== */
#ifndef FLASH_IP_CFG_H
#define FLASH_IP_CFG_H

#include "Std_Types.h"

/* --- PSIZE Enum Mapping --- */
#define FLASH_IP_PSIZE_X8   (0U)  /* Program x8  (1 byte)  */
#define FLASH_IP_PSIZE_X16  (1U)  /* Program x16 (2 bytes) */
#define FLASH_IP_PSIZE_X32  (2U)  /* Program x32 (4 bytes) */
#define FLASH_IP_PSIZE_X64  (3U)  /* Program x64 (8 bytes) */

/* --- Flash ACR Register Configuration --- */
#define FLASH_IP_LATENCY              (2U)
#define FLASH_IP_PREFETCH_ENABLE      (STD_ON)
#define FLASH_IP_ICACHE_ENABLE        (STD_ON)
#define FLASH_IP_DCACHE_ENABLE        (STD_ON)
#define FLASH_IP_TIMEOUT_VALUE        (1048575UL)
#define FLASH_IP_PSIZE                FLASH_IP_PSIZE_X32

/* --- Derived Configuration (tự động tính từ GUI) --- */
#define FLASH_IP_BASE_ADDR            (0x40023C00UL)
#define FLASH_IP_TOTAL_SECTORS        (8U)
#define FLASH_IP_WRITE_ALIGNMENT      (4U)

#endif /* FLASH_IP_CFG_H */
