/* ========================================================================== */
/* AUTOSAR MEMORY DRIVER (MEM) - CONFIGURATION SOURCE                        */
/* Generated by MCAL Configurator Tool - DO NOT EDIT MANUALLY                 */
/* ========================================================================== */
#include "Mem_Cfg.h"

/* ========================================================================== */
/* 1. Sinh mảng cấu hình các Sector Batch của Flash STM32F401RE              */
/* ========================================================================== */
static const Mem_SectorBatchConfigType STM32F401RE_FlashBatches[3] = {

    {
        /* Nhóm 1: 4 Sector (SECTOR_0 -> SECTOR_3) */
        .MemStartAddress       = 0x08000000u,
        .MemNumberOfSectors    = 4u,
        .MemEraseSectorSize    = 16384u, /* 16 KB */
        .MemMinReadSize        = 1u,
        .MemWritePageSize      = 1u,
        .MemSpecifiedEraseCycles = 10000u
    },

    {
        /* Nhóm 2: SECTOR_4 */
        .MemStartAddress       = 0x08010000u,
        .MemNumberOfSectors    = 1u,
        .MemEraseSectorSize    = 65536u, /* 64 KB */
        .MemMinReadSize        = 1u,
        .MemWritePageSize      = 1u,
        .MemSpecifiedEraseCycles = 10000u
    },

    {
        /* Nhóm 3: 3 Sector (SECTOR_5 -> SECTOR_7) */
        .MemStartAddress       = 0x08020000u,
        .MemNumberOfSectors    = 3u,
        .MemEraseSectorSize    = 131072u, /* 128 KB */
        .MemMinReadSize        = 1u,
        .MemWritePageSize      = 1u,
        .MemSpecifiedEraseCycles = 10000u
    }

};

/* ========================================================================== */
/* 2. Sinh mảng Instance (Mem_InstanceConfigType)                             */
/* ========================================================================== */
static const Mem_InstanceConfigType Mem_Instances[MEM_MAX_INSTANCES] = {
    {
        .MemInstanceId      = 0u,
        .MemNumberOfBatches = 3u,
        .MemSectorBatches   = STM32F401RE_FlashBatches
    }
};

/* ========================================================================== */
/* 3. Đóng gói vào biến Root toàn cục [SWS_Mem_10000]                        */
/*    (Chính là biến extern bên file .h)                                      */
/* ========================================================================== */
const Mem_ConfigType Mem_ConfigData = {
    .MemInstances = Mem_Instances
};
