/**********************************************************************************************************************
 * FILE: Flash_IP_Cfg.c
 * Generated by AUTOSAR Mem Configurator 2.0.0. Do not edit manually.
 * Project AUTOSAR release: R25-11
 *********************************************************************************************************************/

#include "Flash_IP_Cfg.h"

const Flash_IP_SectorType Flash_IP_SectorTable[] =
{
    { 0x08000000UL, 0x00004000UL }, /* Sector 0: 16 KB */
    { 0x08004000UL, 0x00004000UL }, /* Sector 1: 16 KB */
    { 0x08008000UL, 0x00004000UL }, /* Sector 2: 16 KB */
    { 0x0800C000UL, 0x00004000UL }, /* Sector 3: 16 KB */
    { 0x08010000UL, 0x00010000UL }, /* Sector 4: 64 KB */
    { 0x08020000UL, 0x00020000UL }, /* Sector 5: 128 KB */
    { 0x08040000UL, 0x00020000UL }, /* Sector 6: 128 KB */
    { 0x08060000UL, 0x00020000UL }  /* Sector 7: 128 KB */
};

#define FLASH_IP_CFG_STATIC_ASSERT(cond, uniqueName) typedef char uniqueName[(cond) ? 1 : -1]

FLASH_IP_CFG_STATIC_ASSERT(
        (sizeof(Flash_IP_SectorTable) / sizeof(Flash_IP_SectorTable[0])) == FLASH_IP_SECTOR_COUNT,
        Flash_IP_Cfg_SectorTableSizeCheck);

#define FLASH_IP_CFG_SECTOR_TOTAL_SIZE_LITERAL \
        (0x00004000UL + 0x00004000UL + 0x00004000UL + \
         0x00004000UL + 0x00010000UL + 0x00020000UL + \
         0x00020000UL + 0x00020000UL)

FLASH_IP_CFG_STATIC_ASSERT(
        FLASH_IP_CFG_SECTOR_TOTAL_SIZE_LITERAL == FLASH_IP_TOTAL_SIZE,
        Flash_IP_Cfg_TotalSizeCheck);
