/**********************************************************************************************************************
 * FILE: Mem_Cfg.c
 * Generated by AUTOSAR Mem Configurator 2.0.0. Do not edit manually.
 * Project AUTOSAR release: R25-11
 *********************************************************************************************************************/

#include "Mem_Cfg.h"

const uint32 Mem_ErasedValue = MEM_ERASED_VALUE;
